### PR TITLE
Adds TypeScript type definitions

### PR DESCRIPTION
**Pull request by OzairP**

### CODE REVIEW

**Comment by flexdinesh** [comment]
@OzairP Is there any compelling reason to switch to Typescript? 
Also we already have an index file which exports Typy. Why do we have typy file renamed to index?

**Comment by OzairP** [comment]
@flexdinesh This adds typescript support for users wanting to use TypeScript with this package and receive full type completion. The `.d.ts` file list type definitions and methods that exist. This will not port any code to TypeScript but simply allow TypeScript to understand the methods and parameters available.

**Comment by flexdinesh** [comment]
@OzairP This package is already published as an npm package and users will be able to import this as any npm package in typescript projects.
Also, I don't think typy would need to be translated to typescript as of now. So I'm gonna close this PR.
Feel free to create another PR if you'd like to fix something or add new type checks to typy. But I'd recommend bringing up project level changes like this by opening an issue/feature request and creating a PR for that. Have a good day!

**Comment by OzairP** [comment]
@flexdinesh I think you're misunderstanding the point of the `index.d.ts` file. Your entire project is written in JavaScript, which has no types or visibilities declared. Yes, I can import this into my TypeScript project, however the compiler has no idea how Typy works, what methods are public or the argument types. The declaration file simply states the methods and types that are required and returned. That way TypeScript projects can use Typy with the type completion and static type check confidence.

This PR is not project level changing, it's a simple 30 line definition file. I am not translating any code, just translating the methods that are publicly exposed.

I highly recommend you read up on the typescript definition files so you fully understand what I'm PR'ing.
https://basarat.gitbooks.io/typescript/docs/types/ambient/d.ts.html

**Comment by flexdinesh** [comment]
@OzairP Apologies. I was not fully aware how typescript works. Now I do. I'm gonna merge these changes. Thanks!

**Pull request merged**
