### PR TITLE
safeObjectOrEmpty

### LINKED ISSUE #19: safeObject should return {} in failure case
I have a lot of code like this:
```ts
function preprocessEmployee(emp: Employee): Employee {
	emp.email = t(emp, "email").safeString;
	emp.info = t(emp, "info").safeObject ? emp.info : <EmployeeInfo>{};
	emp.info.forename = t(emp, "info.forename").safeString;
	emp.info.surname = t(emp, "info.surname").safeString;
	return emp;
}
```
and the emp.info line is annoying to type especially on deeper testings.
It would be nice to replace it with something like
```ts
	emp.info = t(emp, "info").safeObjectOrEmpty;
```
that returns an empty object if the path can not be accessed.

### PR DESCRIPTION
**Pull request by burner**
similar to safeObject but returns a empty object in case path couldn't
be accessed

Fixes #19

### CODE REVIEW

**Comment by flexdinesh** [comment]
@burner Thanks. I'm gonna merge this now and release a small patch this week.

**Comment by burner** [comment]
awesome, thank you

**Comment by flexdinesh** [comment]
v3.0.2 published with changes 🎉

**Comment by burner** [comment]
thank you

**Pull request merged**
